# Generated by Django 4.2.6 on 2023-10-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0019_type_vehicle_driver_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time_from_office', models.TimeField(blank=True, null=True)),
                ('arrival_time_to_destination', models.TimeField(blank=True, null=True)),
                ('departure_time_from_destination', models.TimeField(blank=True, null=True)),
                ('arrival_time_to_office', models.TimeField(blank=True, null=True)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('request_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.request')),
            ],
        ),
    ]
