# Generated by Django 4.2.6 on 2023-10-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0019_type_vehicle_driver_status_and_more'),
        ('trip', '0002_alter_trip_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='request_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.request'),
        ),
    ]
