# Generated by Django 4.2.7 on 2023-11-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_trip_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tripticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
