# Generated by Django 4.2.7 on 2023-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_alter_trip_arrival_time_to_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival_time_to_destination',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival_time_to_office',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time_from_destination',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time_from_office',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
