# Generated by Django 4.2.7 on 2024-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_alter_trip_arrival_time_to_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='id',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
