# Generated by Django 4.2.9 on 2024-04-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_remove_trip_id_trip_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='requestform_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
