# Generated by Django 4.2.4 on 2023-09-03 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.ForeignKey(blank=True, default='Pending', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle_status'),
        ),
    ]
