# Generated by Django 4.2.4 on 2023-09-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_status',
            name='description',
            field=models.CharField(choices=[('available', 'Available'), ('on trip', 'On Trip'), ('unavailable', 'Unavailable')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
