# Generated by Django 4.2.5 on 2023-09-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_alter_vehicle_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='name',
            new_name='vehicle_name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
