# Generated by Django 4.2.5 on 2023-09-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_vehicle_vehicle_image_alter_vehicle_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_status',
            name='description',
            field=models.CharField(choices=[('Available', 'Available'), ('On trip', 'On Trip'), ('Unavailable', 'Unavailable')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
