# Generated by Django 4.2.5 on 2023-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_alter_vehicle_status_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
