# Generated by Django 4.2.5 on 2023-09-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_vehicle_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.ForeignKey(blank=True, default='Available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle_status'),
        ),
    ]
