# Generated by Django 4.2.5 on 2023-09-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_status',
            name='description',
            field=models.CharField(choices=[('Available', 'Available'), ('On trip', 'On Trip'), ('Unavailable', 'Unavailable'), ('Reserved', 'Reserved')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
