# Generated by Django 4.2.5 on 2023-10-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_alter_vehicle_status_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
    ]
