# Generated by Django 4.2.6 on 2023-10-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_remove_vehicle_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle_Status',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_name',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_type',
            new_name='type',
        ),
    ]
