# Generated by Django 4.2.7 on 2024-01-06 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0015_vehicle_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vip_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_vip', to=settings.AUTH_USER_MODEL),
        ),
    ]
