# Generated by Django 4.2.7 on 2024-01-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_remove_vehicle_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('travel_time', models.TimeField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('on_process', models.BooleanField(default=False)),
            ],
        ),
    ]
