# Generated by Django 4.2.7 on 2024-01-20 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_onprocess_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='onprocess',
            name='last_heartbeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
