version: "3.9"

services:
  # Django App
  django_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vehisched_backend:latest
    ports:
      - "8099:8000" # Expose port 8083 for the web server
    environment:
      - PYTHONBUFFERED=1
    command:
      [
        "sh",
        "-c",
        "python vehisched/manage.py collectstatic --noinput && python vehisched/manage.py makemigrations && python vehisched/manage.py migrate && python vehisched/manage.py runserver 0.0.0.0:8000 && python vehisched/manage.py create_periodic_task",
      ]
    volumes:
      - .:/code # For hot reloading
    depends_on:
      - redis

  # Redis Server
  redis:
    image: redis:latest
    ports:
      - "6382:6381" # Expose Redis default port

  # Celery Worker
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: vehisched_backend:latest
    command: celery -A vehisched.config.celery worker --pool=solo -l info
    volumes:
      - .:/code
    depends_on:
      - redis

  # Celery Beat Scheduler
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: vehisched_backend:latest
    command: celery -A vehisched.config.celery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - redis

volumes:
  vehisched:
