version: "3.9"

services:
  # Django App
  django_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vehisched_backend:latest
    ports:
      - "8099:8000" # Expose port 8083 for the web server
    environment:
      - PYTHONBUFFERED=1
    command:
      [
        "sh",
        "-c",
        "python vehisched/manage.py collectstatic --noinput && python vehisched/manage.py makemigrations && python vehisched/manage.py migrate && python vehisched/manage.py runserver 0.0.0.0:8000 && python vehisched/manage.py create_periodic_task",
      ]
    volumes:
      - .:/code # For hot reloading
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3.6.6
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass

  # Redis Server
  redis:
    image: redis:latest
    ports:
      - "6382:6381" # Expose Redis default port
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  # Celery Worker
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: vehisched_backend:latest
    command: celery -A celery worker --pool=solo -l info
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    depends_on:
      - rabbitmq
      - redis

  # Celery Beat Scheduler
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: vehisched_backend:latest
    command: celery -A celery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    depends_on:
      - rabbitmq
      - redis

volumes:
  vehisched:
