# Generated by Django 4.2.4 on 2023-09-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Admin'), ('requester', 'Requester'), ('vip', 'VIP'), ('driver', 'Driver'), ('gate guard', 'Gate Guard'), ('office staff', 'Office Staff')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
