# Generated by Django 4.2.4 on 2023-09-03 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on trip', 'On Trip'), ('unavailable', 'Unavailable')], default='Available', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
