# Generated by Django 4.2.5 on 2023-09-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverStatus',
            new_name='Driver_Status',
        ),
    ]
