# Generated by Django 4.2.5 on 2023-10-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_driver_status_id_alter_driver_status_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver_Status',
        ),
    ]
