# Generated by Django 4.2.5 on 2023-10-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_delete_driver_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_Status',
            fields=[
                ('description', models.CharField(choices=[('Available', 'Available'), ('On trip', 'On Trip'), ('Unavailable', 'Unavailable'), ('Assigned', 'Assigned')], max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
