# Generated by Django 4.2.4 on 2023-09-03 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0006_alter_vehicle_status'),
        ('request', '0008_remove_request_requester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStatus',
            fields=[
                ('fuel_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('tank_balance', models.IntegerField(blank=True, null=True)),
                ('office_stock_issued', models.IntegerField(blank=True, null=True)),
                ('deduct_used_during_trip', models.IntegerField(blank=True, null=True)),
                ('tank_balance_after_trip', models.IntegerField(blank=True, null=True)),
                ('lubricating_office', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speedometer',
            fields=[
                ('speedometer_id', models.AutoField(primary_key=True, serialize=False)),
                ('reading_after_trip', models.IntegerField(blank=True, null=True)),
                ('beginning_of_trip', models.IntegerField(blank=True, null=True)),
                ('distance_traveled', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_passenger', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_time_from_office', models.TimeField(blank=True, null=True)),
                ('arrival_time_to_destination', models.TimeField(blank=True, null=True)),
                ('departure_time_from_destination', models.TimeField(blank=True, null=True)),
                ('arrival_time_to_office', models.TimeField(blank=True, null=True)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('driver_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fuel_status', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tripticket.fuelstatus')),
                ('plate_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle')),
                ('request_number', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.request')),
                ('speedometer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tripticket.speedometer')),
            ],
        ),
    ]
