# Generated by Django 4.2.5 on 2023-10-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripTicket_Status',
            fields=[
                ('description', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Canceled', 'Canceled'), ('Reschedule', 'Reschedule'), ('Completed', 'Completed')], max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
