# Generated by Django 4.2.5 on 2023-10-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripticket', '0002_tripticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripticket',
            name='status',
            field=models.ForeignKey(blank=True, default='Scheduled', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tripticket.tripticket_status'),
        ),
    ]
