# Generated by Django 4.2.5 on 2023-10-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_remove_vehicle_status'),
        ('tripticket', '0003_tripticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripticket',
            name='vehicle_status',
            field=models.ForeignKey(blank=True, default='Reserved', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle_status'),
        ),
    ]
