# Generated by Django 4.2.5 on 2023-10-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_driver_status'),
        ('tripticket', '0004_tripticket_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripticket',
            name='driver_status',
            field=models.ForeignKey(blank=True, default='Assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.driver_status'),
        ),
    ]
