# Generated by Django 4.2.6 on 2023-10-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='travel_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
