# Generated by Django 4.2.4 on 2023-09-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_role_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField()),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('office_or_dept', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_passenger', models.IntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('requester_name', models.ForeignKey(blank=True, limit_choices_to={'role_name': 'requester'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role')),
            ],
        ),
    ]
