# Generated by Django 4.2.4 on 2023-09-02 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_role_role_name'),
        ('request', '0002_alter_request_requester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requester_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
    ]
