# Generated by Django 4.2.4 on 2023-09-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_request_requester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requester_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
