# Generated by Django 4.2.4 on 2023-09-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_role_role_name'),
        ('request', '0004_alter_request_requester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(blank=True, limit_choices_to={'role_name': 'requester'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
    ]
