# Generated by Django 4.2.4 on 2023-09-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_request_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
