# Generated by Django 4.2.4 on 2023-09-03 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0006_alter_vehicle_status'),
        ('request', '0007_request_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='requester',
        ),
        migrations.AlterField(
            model_name='request',
            name='requester_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle'),
        ),
    ]
