# Generated by Django 4.2.5 on 2023-09-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_request_status_request_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(blank=True, default='Pending', null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.request_status'),
        ),
    ]
