# Generated by Django 4.2.5 on 2023-09-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='passenger_names',
            field=models.TextField(blank=True, help_text='List of passenger names in JSON format', null=True),
        ),
    ]
