# Generated by Django 4.2.5 on 2023-10-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_request_is_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_viewed',
        ),
    ]
