# Generated by Django 4.2.6 on 2023-10-19 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_request_return_date_request_return_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Round Trip', 'Round Trip'), ('One-way', 'One-way')], max_length=255)),
                ('sub_category', models.CharField(choices=[('Drop', 'Drop'), ('Fetch', 'Fetch')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.category'),
        ),
    ]
