# Generated by Django 4.2.6 on 2023-10-20 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_request_return_date_request_return_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('description', models.CharField(choices=[('Round Trip', 'Round Trip'), ('One-way', 'One-way')], max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('description', models.CharField(choices=[('Drop', 'Drop'), ('Fetch', 'Fetch'), ('N/A', 'N/A')], max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.category'),
        ),
        migrations.AddField(
            model_name='request',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.sub_category'),
        ),
    ]
