# Generated by Django 4.2.6 on 2023-10-19 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_category_request_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, choices=[('Drop', 'Drop'), ('Fetch', 'Fetch')], max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='request',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.sub_category'),
        ),
    ]
