# Generated by Django 4.2.6 on 2023-10-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0019_type_vehicle_driver_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Awaiting Rescheduling', 'Awaiting Rescheduling')], max_length=255, null=True),
        ),
    ]
