# Generated by Django 4.2.6 on 2023-10-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Approved - Changed Vehicle', 'Approved - Changed Vehicle'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Awaiting Rescheduling', 'Awaiting Rescheduling')], max_length=255, null=True),
        ),
    ]
