# Generated by Django 4.2.7 on 2023-11-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0028_remove_question_answer_remove_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
