# Generated by Django 4.2.7 on 2023-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0032_remove_question_csm_csm_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='from_vip_alteration',
            field=models.BooleanField(default=False),
        ),
    ]
