# Generated by Django 4.2.7 on 2023-12-06 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0033_request_from_vip_alteration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='csm',
            name='question',
        ),
        migrations.RemoveField(
            model_name='csm',
            name='request',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='CSM',
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.question'),
        ),
        migrations.AddField(
            model_name='response',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.request'),
        ),
    ]
