# Generated by Django 4.2.7 on 2024-01-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0035_answer_delete_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='vehicle_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
