# Generated by Django 4.2.7 on 2024-01-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0036_request_vehicle_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='merged_with',
            field=models.TextField(blank=True, null=True),
        ),
    ]
