# Generated by Django 4.2.9 on 2024-03-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0038_request_main_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
