# Generated by Django 4.2.9 on 2024-03-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0039_alter_request_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressFromGoogleMap',
            fields=[
                ('place_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('full_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('estimated_arrival_date_to_destination', models.DateField(blank=True, null=True)),
                ('estimated_arrival_time_to_destination', models.TimeField(blank=True, null=True)),
                ('estimated_return_date_to_ustp', models.DateField(blank=True, null=True)),
                ('estimated_return_time_to_ustp', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
