# Generated by Django 4.2.9 on 2024-03-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0040_addressfromgooglemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressfromgooglemap',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressfromgooglemap',
            name='travel_return_date_gap_in_milliseconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressfromgooglemap',
            name='travel_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
